name: GitLab Sync

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to GitLab
        uses: wangchucheng/git-repo-sync@v0.1.0
        with:
          target-url: ${{ secrets.TARGET_URL }}
          target-username: ${{ secrets.TARGET_USERNAME }}
          target-token: ${{ secrets.TARGET_TOKEN }}
